export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
] as const;

export const memePlusAbi = [
  // === User Write Functions ===
  {
    type: "function",
    name: "register",
    inputs: [
      { name: "referrer", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "invest",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "referrer", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "investFromBalance",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "referrer", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimDailyReturn",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchClaimDailyReturn",
    inputs: [{ name: "users", type: "address[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimMMCompensation",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // === Admin Write Functions ===
  {
    type: "function",
    name: "addAdmin",
    inputs: [{ name: "account", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeAdmin",
    inputs: [{ name: "account", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pauseMember",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpauseMember",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "freezeMember",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unfreezeMember",
    inputs: [{ name: "member", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCommunityLevel",
    inputs: [
      { name: "member", type: "address" },
      { name: "level", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCommunityLevelBatch",
    inputs: [
      { name: "members", type: "address[]" },
      { name: "levels", type: "uint8[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMemberVLevel",
    inputs: [
      { name: "member", type: "address" },
      { name: "level", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMemberVLevelBatch",
    inputs: [
      { name: "members", type: "address[]" },
      { name: "levels", type: "uint8[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "restart",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "globalRestart",
    inputs: [{ name: "users", type: "address[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rescueTokens",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settle",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPerpetualBCKPercent",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setBCKPrice",
    inputs: [{ name: "val", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSettlementInterval",
    inputs: [{ name: "val", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setReceiverWallet",
    inputs: [{ name: "_wallet", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeCollector",
    inputs: [{ name: "_collector", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCapMultiplier",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDailyReturnRate",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinInvestment",
    inputs: [{ name: "val", type: "uint128" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinWithdrawal",
    inputs: [{ name: "val", type: "uint128" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setWithdrawalFee",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setStaticDynamicSplit",
    inputs: [
      { name: "_static", type: "uint16" },
      { name: "_dynamic", type: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setStaticDistribution",
    inputs: [
      { name: "_toBalance", type: "uint16" },
      { name: "_toBurn", type: "uint16" },
      { name: "_toLock", type: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDynamicPoolSplit",
    inputs: [
      { name: "_referral", type: "uint16" },
      { name: "_team", type: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setReferralRates",
    inputs: [
      { name: "_gen1", type: "uint16" },
      { name: "_gen2", type: "uint16" },
      { name: "_gen3", type: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCommunityRates",
    inputs: [{ name: "rates", type: "uint16[5]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVLevelRates",
    inputs: [{ name: "rates", type: "uint16[6]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVLevelThresholds",
    inputs: [{ name: "thresholds", type: "uint128[6]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSameLevelBonus",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRestartMMCompPercent",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRestartMMReleaseRate",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRestartReferralRate",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRestartReferralCap",
    inputs: [{ name: "val", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // === Settlement Combined ===
  {
    type: "function",
    name: "settleAndBatchClaim",
    inputs: [{ name: "users", type: "address[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // === V-Level Recalculate ===
  {
    type: "function",
    name: "recalculateVLevels",
    inputs: [{ name: "users", type: "address[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // === DataClean Functions ===
  {
    type: "function",
    name: "purgeNonAdminData",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // === Read Functions ===
  {
    type: "function",
    name: "getMemberInfo",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "referrer", type: "address" },
      { name: "vLevel", type: "uint8" },
      { name: "communityLevel", type: "uint8" },
      { name: "isActive", type: "bool" },
      { name: "isFrozen", type: "bool" },
      { name: "isPaused", type: "bool" },
      { name: "isRestarted", type: "bool" },
      { name: "totalInvested", type: "uint256" },
      { name: "totalWithdrawn", type: "uint256" },
      { name: "balance", type: "uint256" },
      { name: "totalEarned", type: "uint256" },
      { name: "directReferralCount", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrders",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "amount", type: "uint128" },
          { name: "totalReturned", type: "uint128" },
          { name: "createdAt", type: "uint32" },
          { name: "lastClaimedAt", type: "uint32" },
          { name: "isActive", type: "bool" },
          { name: "lastClaimedEpoch", type: "uint32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrderCount",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isMemberRegistered",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTeamInfo",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "teamPerf", type: "uint256" },
      { name: "smallZonePerf", type: "uint256" },
      { name: "directCount", type: "uint256" },
      { name: "vLevel", type: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRestartInfo",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "unreturnedCapital", type: "uint128" },
      { name: "referralEarned", type: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenLock",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "amount", type: "uint128" },
      { name: "originalAmount", type: "uint128" },
      { name: "lockedAt", type: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBCKLock",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "amount", type: "uint128" },
      { name: "originalAmount", type: "uint128" },
      { name: "lockedAt", type: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimBCKRelease",
    inputs: [{ name: "user", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getDirectReferrals",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTeamPerformance",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSmallZonePerformance",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBranchPerformance",
    inputs: [
      { name: "user", type: "address" },
      { name: "directRef", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCommunityEarned",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllMembersCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMemberAtIndex",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },

  // === Config Read Functions ===
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAdmin",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minInvestment",
    inputs: [],
    outputs: [{ name: "", type: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minWithdrawal",
    inputs: [],
    outputs: [{ name: "", type: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawalFee",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "capMultiplier",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dailyReturnRate",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "staticPercent",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dynamicPercent",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "staticToBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "staticToBurn",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "staticToLock",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "referralSharePercent",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "teamSharePercent",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "referralGen1",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "referralGen2",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "referralGen3",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sameLevelBonus",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "communityRates",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vLevelRates",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vLevelThresholds",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeCollector",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "restartMMCompPercent",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "restartMMReleaseRate",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "restartReferralRate",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "restartReferralCap",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "perpetualBCKPercent",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bckPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "receiverWallet",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settlementInterval",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentEpoch",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentEpoch",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPendingRewards",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDSRInfo",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "activeStake", type: "uint128" },
      { name: "pendingRewards", type: "uint256" },
      { name: "totalRawReturn", type: "uint256" },
      { name: "userRewardPerTokenPaid", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "genesisTimestamp",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rewardPerTokenStored",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastUpdateEpoch",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastSettledAt",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },

  // === Events ===
  {
    type: "event",
    name: "Invested",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "referrer", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "grossAmount", type: "uint256", indexed: false },
      { name: "fee", type: "uint256", indexed: false },
      { name: "netAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "index", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DailyReturnClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "totalReturn", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MemberRegistered",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "referrer", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "BalanceUpdated",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "newBalance", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AccountRestarted",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "unreturnedCapital", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VLevelUpgraded",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "oldLevel", type: "uint8", indexed: false },
      { name: "newLevel", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ReferralRewardPaid",
    inputs: [
      { name: "investor", type: "address", indexed: true },
      { name: "referrer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "generation", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TeamRewardPaid",
    inputs: [
      { name: "investor", type: "address", indexed: true },
      { name: "ancestor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "rewardType", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CommunityIncomePaid",
    inputs: [
      { name: "investor", type: "address", indexed: true },
      { name: "ancestor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "level", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ParameterUpdated",
    inputs: [
      { name: "name", type: "string", indexed: false },
      { name: "value", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Paused",
    inputs: [],
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [],
  },
  {
    type: "event",
    name: "AdminAdded",
    inputs: [
      { name: "account", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "AdminRemoved",
    inputs: [
      { name: "account", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "GlobalRestartExecuted",
    inputs: [
      { name: "count", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MMCompensationClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ReferralCompensationClaimed",
    inputs: [
      { name: "restartedUser", type: "address", indexed: true },
      { name: "referredUser", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },

  // === Errors ===
  { type: "error", name: "BelowMinInvestment", inputs: [] },
  { type: "error", name: "NotMultipleOf100", inputs: [] },
  { type: "error", name: "BelowMinWithdrawal", inputs: [] },
  { type: "error", name: "NotMultipleOf10", inputs: [] },
  { type: "error", name: "AccountFrozen", inputs: [] },
  { type: "error", name: "AccountPaused", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "NotActive", inputs: [] },
  { type: "error", name: "NotRegistered", inputs: [] },
  { type: "error", name: "ContractPaused", inputs: [] },
  { type: "error", name: "AlreadyRegistered", inputs: [] },
  { type: "error", name: "CannotReferSelf", inputs: [] },
  { type: "error", name: "FeeTooHigh", inputs: [] },
  { type: "error", name: "InvalidLevel", inputs: [] },
  { type: "error", name: "InvalidIndex", inputs: [] },
  { type: "error", name: "MustSumTo10000", inputs: [] },
  { type: "error", name: "NotAdmin", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "NotRestarted", inputs: [] },
  { type: "error", name: "NothingToRestart", inputs: [] },
  { type: "error", name: "NoMMToClaim", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "TooEarly", inputs: [] },
  { type: "error", name: "ArrayLengthMismatch", inputs: [] },
  { type: "error", name: "ReferrerNotRegistered", inputs: [] },
  { type: "error", name: "NoBCKToClaim", inputs: [] },
  { type: "error", name: "NoActiveOrders", inputs: [] },
  { type: "error", name: "BatchTooLarge", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },

  // Diamond events
  {
    type: "event",
    name: "OrderCapped",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "orderIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BCKLocked",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "bckAmount", type: "uint256", indexed: false },
      { name: "unreturnedCapital", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BCKReleased",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EpochSettled",
    inputs: [
      { name: "epoch", type: "uint256", indexed: true },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
] as const;
